/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include "catch.hpp"
#include "utils.hpp"
#include "processor.hpp"

#include <osmium/io/any_compression.hpp>
#include <osmium/io/xml_input.hpp>

TEST_CASE("Single node") {
  SECTION("Should select the node for extraction") {
    using id_set = std_id_set;
    typedef osmium::io::InputIterator<osmium::io::Reader, osmium::OSMObject> obj_iterator;

    osmium::io::File file(test_data_file("test_single_node.osm"));
    osmium::Box box(osmium::Location(double(-180), double(-90)),
                    osmium::Location(double( 180), double( 90)));

    osmium::io::Reader reader(file, osmium::osm_entity_bits::nwr);
    obj_iterator it(reader);
    const obj_iterator end;

    id_set nodes = hsplitter::detail::find_nodes_in_bbox<id_set>(it, end, box);

    REQUIRE(nodes.m_set.size() == 1);
    REQUIRE(nodes.has(1));
  }

  SECTION("Should extract the node when it is in the extraction box") {
    using id_set = std_id_set;

    osmium::io::File file(test_data_file("test_single_node.osm"));
    osmium::Box box(osmium::Location(double(-180), double(-90)),
                    osmium::Location(double( 180), double( 90)));

    hsplitter::HistoryExtractReader<id_set> reader =
      hsplitter::read_extract<id_set>(file, box);

    REQUIRE(!reader.eof());
    osmium::memory::Buffer buffer = reader.read();
    REQUIRE(std::distance(buffer.begin(), buffer.end()) == 1);
    REQUIRE(buffer.get<osmium::memory::Item>(0).type() == osmium::item_type::node);
    auto &node = buffer.get<osmium::Node>(0);
    REQUIRE(node.id() == 1);
  }

  SECTION("Should not extract the node when it is outside the bounding box") {
    using id_set = std_id_set;

    osmium::io::File file(test_data_file("test_single_node.osm"));
    osmium::Box box(osmium::Location(double(-180), double(-90)),
                    osmium::Location(double(-179), double( 90)));

    hsplitter::HistoryExtractReader<id_set> reader =
      hsplitter::read_extract<id_set>(file, box);

    REQUIRE(!reader.eof());
    osmium::memory::Buffer buffer = reader.read();
    REQUIRE(std::distance(buffer.begin(), buffer.end()) == 0);
  }
}
