/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include "catch.hpp"
#include "chunked_array.hpp"

using hsplitter::container::chunked_array;

TEST_CASE("Chunked array") {
  SECTION("should act like a container in one chunk") {
    chunked_array<int, 20> array;
    array.push_back(1);
    array.push_back(2);
    array.push_back(3);
    array.push_back(4);
    array.push_back(5);

    REQUIRE(array.size() == 5);
    REQUIRE((array.end() - array.begin()) == 5);

    auto itr = array.begin();
    REQUIRE(*itr == 1); ++itr;
    REQUIRE(*itr == 2); ++itr;
    REQUIRE(*itr == 3); ++itr;
    REQUIRE(*itr == 4); ++itr;
    REQUIRE(*itr == 5); ++itr;
    REQUIRE(itr == array.end());
  }

  SECTION("should act like a container with many chunks") {
    chunked_array<int, 2> array;
    array.push_back(1);
    array.push_back(2);
    array.push_back(3);
    array.push_back(4);
    array.push_back(5);

    REQUIRE(array.size() == 5);
    REQUIRE((array.end() - array.begin()) == 5);

    auto itr = array.begin();
    REQUIRE(*itr == 1); ++itr;
    REQUIRE(*itr == 2); ++itr;
    REQUIRE(*itr == 3); ++itr;
    REQUIRE(*itr == 4); ++itr;
    REQUIRE(*itr == 5); ++itr;
    REQUIRE(itr == array.end());
  }

  SECTION("should default construct to empty") {
    chunked_array<int, 100> array;
    REQUIRE(array.empty());
    REQUIRE(array.begin() == array.end());
    REQUIRE(array.size() == 0);
  }

  SECTION("should be able to reverse iterate") {
    chunked_array<int, 2> array;
    array.push_back(1);
    array.push_back(2);
    array.push_back(3);
    array.push_back(4);
    array.push_back(5);

    REQUIRE(array.size() == 5);
    REQUIRE((array.end() - array.begin()) == 5);

    auto itr = array.end();
    --itr; REQUIRE(*itr == 5);
    --itr; REQUIRE(*itr == 4);
    --itr; REQUIRE(*itr == 3);
    --itr; REQUIRE(*itr == 2);
    --itr; REQUIRE(*itr == 1);
    REQUIRE(itr == array.begin());
  }

  SECTION("should be able to do reverse iterator arithmetic") {
    chunked_array<int, 2> array;
    array.push_back(1);
    array.push_back(2);
    array.push_back(3);
    array.push_back(4);
    array.push_back(5);

    REQUIRE(array.size() == 5);
    REQUIRE((array.end() - array.begin()) == 5);

    auto itr = array.end();
    REQUIRE(*(itr - 1) == 5);
    REQUIRE(*(itr - 2) == 4);
    REQUIRE(*(itr - 3) == 3);
    REQUIRE(*(itr - 4) == 2);
    REQUIRE(*(itr - 5) == 1);

    REQUIRE(itr[-1] == 5);
    REQUIRE(itr[-2] == 4);
    REQUIRE(itr[-3] == 3);
    REQUIRE(itr[-4] == 2);
    REQUIRE(itr[-5] == 1);
  }

  SECTION("should be sortable") {
    chunked_array<int, 20> array;
    for (int i = 0; i <= 100; ++i) {
      array.push_back(100 - i);
    }

    REQUIRE(array.size() == 101);
    REQUIRE((array.end() - array.begin()) == 101);

    std::sort(array.begin(), array.end());

    REQUIRE(array.size() == 101);
    REQUIRE((array.end() - array.begin()) == 101);

    for (int i = 0; i <= 100; ++i) {
      auto itr = array.begin() + i;
      REQUIRE(*itr == i);
      REQUIRE(array.begin()[i] == i);
    }
  }
}
