/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include "catch.hpp"
#include "splitter.hpp"
#include "tileset.hpp"

#include <osmium/memory/buffer.hpp>
#include <osmium/builder/osm_object_builder.hpp>

#include <vector>
#include <map>
#include <set>

namespace {
void push_back_way(osmium::memory::Buffer &ways,
                   osmium::object_id_type id,
                   osmium::object_version_type version,
                   bool visible,
                   osmium::changeset_id_type changeset_id,
                   osmium::user_id_type uid,
                   std::vector<osmium::object_id_type> nds) {
  osmium::builder::WayBuilder builder(ways);
  osmium::Way &way = builder.object();
  way.set_id(id);
  way.set_version(version);
  way.set_visible(visible);
  way.set_changeset(changeset_id);
  way.set_uid(uid);
  way.set_timestamp(0);
  builder.add_user("testuser");

  {
    osmium::builder::WayNodeListBuilder wnl_builder(ways, &builder);
    for (auto nd_id : nds) {
      wnl_builder.add_node_ref(nd_id);
    }
  }

  ways.commit();
}
} // anonymous namespace

TEST_CASE("Split ways") {
  SECTION("should put way in the right bucket.") {
    using map_t = tileset;
    constexpr size_t buffer_size = 10000;
    unsigned char data[buffer_size];

    map_t node_tiles;
    node_tiles.m_map[1] = std::set<hsplitter::tile_t>({1});
    node_tiles.m_map[2] = std::set<hsplitter::tile_t>({1});
    node_tiles.m_map[3] = std::set<hsplitter::tile_t>({1});
    node_tiles.freeze();

    osmium::memory::Buffer ways(data, buffer_size, 0);

    push_back_way(ways, 1, 1, true, 1, 1, {1, 2, 3});

    REQUIRE(std::distance(ways.begin(), ways.end()) == 1);

    auto it = ways.begin();
    auto pair = hsplitter::tiles_for_ways<map_t>(it, ways.end(), node_tiles);
    map_t way_tiles = std::move(pair.first);
    map_t extra_node_tiles = std::move(pair.second);

    REQUIRE(way_tiles.m_map.size() == 1);
    REQUIRE(way_tiles.m_map.count(1) == 1);
    REQUIRE(way_tiles.m_map[1].size() == 1);
    REQUIRE(way_tiles.m_map[1].count(1) == 1);

    REQUIRE(extra_node_tiles.m_map.size() == 3);
    REQUIRE(extra_node_tiles.m_map.count(1) == 1);
    REQUIRE(extra_node_tiles.m_map[1].size() == 1);
    REQUIRE(extra_node_tiles.m_map[1].count(1) == 1);
    REQUIRE(extra_node_tiles.m_map.count(2) == 1);
    REQUIRE(extra_node_tiles.m_map[2].size() == 1);
    REQUIRE(extra_node_tiles.m_map[2].count(1) == 1);
    REQUIRE(extra_node_tiles.m_map.count(3) == 1);
    REQUIRE(extra_node_tiles.m_map[3].size() == 1);
    REQUIRE(extra_node_tiles.m_map[3].count(1) == 1);
  }

  SECTION("way should cause nodes to be put in extra buckets.") {
    using map_t = tileset;
    constexpr size_t buffer_size = 10000;
    unsigned char data[buffer_size];

    map_t node_tiles;
    node_tiles.m_map[1] = std::set<hsplitter::tile_t>({1});
    node_tiles.m_map[2] = std::set<hsplitter::tile_t>({2});
    node_tiles.m_map[3] = std::set<hsplitter::tile_t>({3});
    node_tiles.freeze();

    osmium::memory::Buffer ways(data, buffer_size, 0);

    push_back_way(ways, 1, 1, true, 1, 1, {1, 2, 3});

    REQUIRE(std::distance(ways.begin(), ways.end()) == 1);

    auto it = ways.begin();
    auto pair = hsplitter::tiles_for_ways<map_t>(it, ways.end(), node_tiles);
    map_t way_tiles = std::move(pair.first);
    map_t extra_node_tiles = std::move(pair.second);

    REQUIRE(way_tiles.m_map.size() == 1);
    REQUIRE(way_tiles.m_map.count(1) == 1);
    REQUIRE(way_tiles.m_map[1].size() == 3);
    REQUIRE(way_tiles.m_map[1].count(1) == 1);
    REQUIRE(way_tiles.m_map[1].count(2) == 1);
    REQUIRE(way_tiles.m_map[1].count(3) == 1);

    REQUIRE(extra_node_tiles.m_map[1].size() == 3);
    REQUIRE(extra_node_tiles.m_map[1].count(1) == 1);
    REQUIRE(extra_node_tiles.m_map[1].count(2) == 1);
    REQUIRE(extra_node_tiles.m_map[1].count(3) == 1);
    REQUIRE(extra_node_tiles.m_map[2].size() == 3);
    REQUIRE(extra_node_tiles.m_map[2].count(1) == 1);
    REQUIRE(extra_node_tiles.m_map[2].count(2) == 1);
    REQUIRE(extra_node_tiles.m_map[2].count(3) == 1);
    REQUIRE(extra_node_tiles.m_map[3].size() == 3);
    REQUIRE(extra_node_tiles.m_map[3].count(1) == 1);
    REQUIRE(extra_node_tiles.m_map[3].count(2) == 1);
    REQUIRE(extra_node_tiles.m_map[3].count(3) == 1);
  }
}
