/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include "catch.hpp"
#include "splitter.hpp"

#include <osmium/memory/buffer.hpp>
#include <osmium/builder/osm_object_builder.hpp>

#include <vector>
#include <map>
#include <set>

namespace {
void push_back_rel(osmium::memory::Buffer &rels,
                   osmium::object_id_type id,
                   osmium::object_version_type version,
                   bool visible,
                   osmium::changeset_id_type changeset_id,
                   osmium::user_id_type uid,
                   std::vector<osmium::object_id_type> node_mbrs,
                   std::vector<osmium::object_id_type> way_mbrs,
                   std::vector<osmium::object_id_type> rel_mbrs) {
  osmium::builder::RelationBuilder builder(rels);
  osmium::Relation &rel = builder.object();
  rel.set_id(id);
  rel.set_version(version);
  rel.set_visible(visible);
  rel.set_changeset(changeset_id);
  rel.set_uid(uid);
  rel.set_timestamp(0);
  builder.add_user("testuser");

  {
    osmium::builder::RelationMemberListBuilder mbr_builder(rels, &builder);
    // in Real Life, we can get relations with members in any order
    // and with arbitrary roles, but it makes it way simpler to
    // generate test data if they all have no role and come in the
    // order nodes, ways, relations.
    for (auto node_id : node_mbrs) {
    mbr_builder.add_member(osmium::item_type::node, node_id, "", 0, nullptr);
    }
    for (auto way_id : way_mbrs) {
      mbr_builder.add_member(osmium::item_type::way, way_id, "", 0, nullptr);
    }
    for (auto rel_id : rel_mbrs) {
      mbr_builder.add_member(osmium::item_type::relation, rel_id, "", 0, nullptr);
    }
  }

  rels.commit();
}
} // anonymous namespace

TEST_CASE("Split relations") {
  SECTION("should put relation in the right bucket.") {
    using map_t = std::map<hsplitter::tile_t, std::set<hsplitter::tile_t> >;
    constexpr size_t buffer_size = 10000;
    unsigned char data[buffer_size];

    map_t node_tiles, way_tiles, extra_node_tiles;
    node_tiles[1] = std::set<hsplitter::tile_t>({1});
    node_tiles[2] = std::set<hsplitter::tile_t>({1});
    node_tiles[3] = std::set<hsplitter::tile_t>({1});

    osmium::memory::Buffer rels(data, buffer_size, 0);

    push_back_rel(rels, 1, 1, true, 1, 1, {1, 2, 3}, {}, {});

    REQUIRE(std::distance(rels.begin(), rels.end()) == 1);

    auto it = rels.begin();
    auto pair = hsplitter::tiles_for_relations<map_t>(it, rels.end(), node_tiles, way_tiles, extra_node_tiles);
    map_t rel_tiles = std::move(pair.first);
    map_t extra_rel_tiles = std::move(pair.second);

    REQUIRE(rel_tiles.size() == 1);
    REQUIRE(rel_tiles.count(1) == 1);
    REQUIRE(rel_tiles[1].size() == 1);
    REQUIRE(rel_tiles[1].count(1) == 1);
    REQUIRE(extra_rel_tiles.empty());
  }
}
