/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include "catch.hpp"
#include "vx2fmt.hpp"

#include <sstream>

TEST_CASE("VX2 Format") {
  SECTION("Should write the header magic") {
    std::ostringstream out;
    vx2fmt::dict_t headers;

    REQUIRE(vx2fmt::write_vx2fmt_header(out, headers) == true);

    auto output = out.str();
    REQUIRE(output.size() >= 6);
    REQUIRE(output[0] == 'V');
    REQUIRE(output[1] == 'X');
    REQUIRE(output[2] == '2');
    REQUIRE(output[3] == 'F');
    REQUIRE(output[4] == 'M');
    REQUIRE(output[5] == 'T');
  }

  SECTION("Should be able to read an empty header") {
    std::stringstream stream;
    vx2fmt::dict_t headers;

    REQUIRE(vx2fmt::write_vx2fmt_header(stream, headers) == true);

    stream.seekg(0);
    REQUIRE(vx2fmt::read_vx2fmt_header(stream, headers) == true);
    REQUIRE(headers.empty());
  }

  SECTION("Should be able to read some headers") {
    std::stringstream stream;
    vx2fmt::dict_t out_headers, in_headers;
    out_headers.insert(std::make_pair<std::string>("foo", "bar"));
    out_headers.insert(std::make_pair<std::string>("baz", "bat"));
    
    REQUIRE(vx2fmt::write_vx2fmt_header(stream, out_headers) == true);

    stream.seekg(0);
    REQUIRE(vx2fmt::read_vx2fmt_header(stream, in_headers) == true);

    REQUIRE(in_headers.size() == out_headers.size());
    for (const auto &val : out_headers) {
      REQUIRE(in_headers.count(val.first) == 1);
      REQUIRE(in_headers[val.first] == val.second);
    }
  }

  SECTION("Should be able to have empty keys and values in headers") {
    std::stringstream stream;
    vx2fmt::dict_t out_headers, in_headers;
    out_headers.insert(std::make_pair<std::string>("foo", ""));
    out_headers.insert(std::make_pair<std::string>("", "bat"));
    
    REQUIRE(vx2fmt::write_vx2fmt_header(stream, out_headers) == true);

    stream.seekg(0);
    REQUIRE(vx2fmt::read_vx2fmt_header(stream, in_headers) == true);

    REQUIRE(in_headers.size() == out_headers.size());
    for (const auto &val : out_headers) {
      REQUIRE(in_headers.count(val.first) == 1);
      REQUIRE(in_headers[val.first] == val.second);
    }
  }
}
