/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include "catch.hpp"
#include "splitter.hpp"

#include <osmium/memory/buffer.hpp>
#include <osmium/builder/osm_object_builder.hpp>

#include <vector>
#include <map>
#include <set>

TEST_CASE("Split nodes") {
  SECTION("should put node in the right bucket.") {
    using map_t = std::map<hsplitter::tile_t, std::set<hsplitter::tile_t> >;
    constexpr size_t buffer_size = 10000;
    unsigned char data[buffer_size];

    osmium::memory::Buffer nodes(data, buffer_size, 0);
    {
      osmium::builder::NodeBuilder builder(nodes);
      osmium::Node &node = builder.object();
      node.set_id(1);
      node.set_version(1);
      node.set_visible(true);
      node.set_changeset(1);
      node.set_uid(1);
      node.set_timestamp(0);
      node.set_location(osmium::Location(-180.0, 85.0511287));

      builder.add_user("testuser");

      nodes.commit();
    }

    REQUIRE(std::distance(nodes.begin(), nodes.end()) == 1);

    auto it = nodes.begin();
    auto tiles = hsplitter::tiles_for_nodes<map_t>(it, nodes.end());

    REQUIRE(tiles.size() == 1);
    REQUIRE(tiles.count(1) == 1);
    REQUIRE(tiles[1].size() == 1);
    REQUIRE(tiles[1].count(0) == 1);
  }

  SECTION("Should put multiple locations for node versions in set") {
    using map_t = std::map<hsplitter::tile_t, std::set<hsplitter::tile_t> >;
    constexpr size_t buffer_size = 10000;
    unsigned char data[buffer_size];

    osmium::memory::Buffer nodes(data, buffer_size, 0);
    {
      osmium::builder::NodeBuilder builder(nodes);
      osmium::Node &node = builder.object();
      node.set_id(1);
      node.set_version(1);
      node.set_visible(true);
      node.set_changeset(1);
      node.set_uid(1);
      node.set_timestamp(0);
      node.set_location(osmium::Location(-180.0, 85.0511287));

      builder.add_user("testuser");

      nodes.commit();
    }
    {
      osmium::builder::NodeBuilder builder(nodes);
      osmium::Node &node = builder.object();
      node.set_id(1);
      node.set_version(2);
      node.set_visible(true);
      node.set_changeset(1);
      node.set_uid(1);
      node.set_timestamp(0);
      node.set_location(osmium::Location(180.0, -85.0511287));

      builder.add_user("testuser");

      nodes.commit();
    }

    REQUIRE(std::distance(nodes.begin(), nodes.end()) == 2);

    auto it = nodes.begin();
    auto tiles = hsplitter::tiles_for_nodes<map_t>(it, nodes.end());

    REQUIRE(tiles.size() == 1);
    REQUIRE(tiles.count(1) == 1);
    REQUIRE(tiles[1].size() == 2);
    REQUIRE(tiles[1].count(0) == 1);
    REQUIRE(tiles[1].count(0xfffffffful) == 1);
  }

  SECTION("Should put multiple nodes in different sets") {
    using map_t = std::map<hsplitter::tile_t, std::set<hsplitter::tile_t> >;
    constexpr size_t buffer_size = 10000;
    unsigned char data[buffer_size];

    osmium::memory::Buffer nodes(data, buffer_size, 0);
    {
      osmium::builder::NodeBuilder builder(nodes);
      osmium::Node &node = builder.object();
      node.set_id(1);
      node.set_version(1);
      node.set_visible(true);
      node.set_changeset(1);
      node.set_uid(1);
      node.set_timestamp(0);
      node.set_location(osmium::Location(-180.0, 85.0511287));

      builder.add_user("testuser");

      nodes.commit();
    }
    {
      osmium::builder::NodeBuilder builder(nodes);
      osmium::Node &node = builder.object();
      node.set_id(2);
      node.set_version(1);
      node.set_visible(true);
      node.set_changeset(1);
      node.set_uid(1);
      node.set_timestamp(0);
      node.set_location(osmium::Location(180.0, -85.0511287));

      builder.add_user("testuser");

      nodes.commit();
    }

    REQUIRE(std::distance(nodes.begin(), nodes.end()) == 2);

    auto it = nodes.begin();
    auto tiles = hsplitter::tiles_for_nodes<map_t>(it, nodes.end());

    REQUIRE(tiles.size() == 2);
    REQUIRE(tiles.count(1) == 1);
    REQUIRE(tiles[1].size() == 1);
    REQUIRE(tiles[1].count(0) == 1);
    REQUIRE(tiles.count(2) == 1);
    REQUIRE(tiles[2].size() == 1);
    REQUIRE(tiles[2].count(0xfffffffful) == 1);
  }
}
