#ifndef OSMIUM_HISTORY_SPLITTER_VX2FMT_HPP
#define OSMIUM_HISTORY_SPLITTER_VX2FMT_HPP

/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <map>
#include <string>
#include <istream>
#include <ostream>

namespace vx2fmt {

typedef std::map<std::string, std::string> dict_t;

bool write_header(std::ostream &out, const dict_t &headers);

bool read_header(std::istream &in, dict_t &headers);

bool write_metadata(std::ostream &out,
                    uint64_t id, uint64_t version, uint64_t uid, uint64_t unix_timestamp,
                    uint64_t changeset_id, bool visible);

bool read_metadata(std::istream &in,
                   uint64_t &id, uint64_t &version, uint64_t &uid, uint64_t &unix_timestamp,
                   uint64_t &changeset_id, bool &visible);

bool write_tags(std::ostream &out, const dict_t &tags);

bool read_tags(std::istream &in, dict_t &tags);

} // namespace vx2fmt

#endif // OSMIUM_HISTORY_SPLITTER_VX2FMT_HPP
