#ifndef OSMIUM_HISTORY_SPLITTER_SPLITTER_HPP
#define OSMIUM_HISTORY_SPLITTER_SPLITTER_HPP

/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <osmium/geom/coordinates.hpp>
#include <osmium/geom/mercator_projection.hpp>
#include <osmium/osm/node.hpp>
#include <osmium/osm/way.hpp>
#include <osmium/osm/relation.hpp>

#include <unordered_map>
#include <unordered_set>

namespace hsplitter {

using tile_t = uint32_t;

inline uint32_t interleave(uint32_t n) {
  n &= 0x0000ffffUL;
  n = (n | (n <<  8)) & 0x00ff00ffUL;
  n = (n | (n <<  4)) & 0x0f0f0f0fUL;
  n = (n | (n <<  2)) & 0x33333333UL;
  n = (n | (n <<  1)) & 0x55555555UL;
  return n;
}

inline tile_t morton_code(uint16_t x, uint16_t y) {
  return (interleave(x) << 1) | interleave(y);
}

template <typename Item>
struct osmium_item_type {};

template <>
struct osmium_item_type<osmium::Node> {
  static const osmium::item_type type = osmium::item_type::node;
};

template <>
struct osmium_item_type<osmium::Way> {
  static const osmium::item_type type = osmium::item_type::way;
};

template <>
struct osmium_item_type<osmium::Relation> {
  static const osmium::item_type type = osmium::item_type::relation;
};

template <typename Item, typename Iterator, typename Func>
inline void iterate(Iterator &it, const Iterator &end, Func func) {
  while ((it != end) && (it->type() == osmium_item_type<Item>::type)) {
    const Item &item = static_cast<const Item &>(*it);
    func(item);
    ++it;
  }
}

template <typename TileSet, typename Iterator>
inline TileSet tiles_for_nodes(Iterator &it, const Iterator &end) {
  static const double max_coord = osmium::geom::detail::max_coordinate_epsg3857;
  TileSet tiles;

  iterate<osmium::Node>(it, end, [&tiles] (const osmium::Node &node) {
      if (node.visible() && node.location().valid()) {
        // note: we've already checked for validity, no need to do it
        // again.
        double lat = node.location().lat_without_check();

        // nodes outside this range can't be projected to web mercator
        // tiles.
        if ((lat >= -osmium::geom::MERCATOR_MAX_LAT) &&
            (lat <= osmium::geom::MERCATOR_MAX_LAT)) {
          // project to mercator space - we'll use that for splitting
          // into tiles so that it matches the z/x/y (for z=16) that
          // people expect.
          osmium::geom::Coordinates coords(node.location().lon_without_check(), lat);
          coords = osmium::geom::lonlat_to_mercator(coords);

          // tiles are named by the morton code of the x,y coord pair.
          // clamp tile coords to 0, 65535 to avoid overflow.
          double x = double(1 << 16) * 0.5 * (coords.x + max_coord) / max_coord;
          if (x <     0.0) { x =     0.0; }
          if (x > 65535.0) { x = 65535.0; }
          double y = double(1 << 16) * 0.5 * (max_coord - coords.y) / max_coord;
          if (y <     0.0) { y =     0.0; }
          if (y > 65535.0) { y = 65535.0; }

          auto tile_id = morton_code(uint16_t(x), uint16_t(y));
          tiles.insert(node.id(), tile_id);
        }
      }
    });

  return std::move(tiles);
}

// returns a pair of (way_tiles, extra_node_tiles).
template <typename TileSet, typename Iterator>
inline std::pair<TileSet, TileSet> tiles_for_ways(Iterator &it, const Iterator &end,
                                                  const TileSet &node_tiles) {
  TileSet way_tiles, extra_node_tiles;

  iterate<osmium::Way>(it, end, [&way_tiles, &extra_node_tiles, &node_tiles] (const osmium::Way &way) {
      if (way.visible()) {
        const auto way_id = way.id();

        for (const auto &nd : way.nodes()) {
          auto range = node_tiles.equal_range(nd.ref());

          for (auto tile : range) {
            way_tiles.insert(way_id, tile);
          }
        }

        auto range = way_tiles.equal_range(way_id);
        for (const auto &nd : way.nodes()) {
          const auto node_id = nd.ref();

          for (auto tile : range) {
            extra_node_tiles.insert(node_id, tile);
          }
        }
      }
    });

  return std::move(std::make_pair(std::move(way_tiles), std::move(extra_node_tiles)));
}

namespace detail {
template <typename TileSet>
inline void add_tiles_for_id(const TileSet &from,
                             typename TileSet::key_type from_id,
                             TileSet &to,
                             typename TileSet::key_type to_id) {
  auto range = from.equal_range(from_id);

  for (auto tile : range) {
    to.insert(to_id, tile);
  }
}
} // namespace detail

template <typename TileSet, typename Iterator>
std::pair<TileSet, TileSet> tiles_for_relations(Iterator &it, const Iterator &end,
                                                const TileSet &node_tiles,
                                                const TileSet &way_tiles,
                                                const TileSet &extra_node_tiles) {
  using detail::add_tiles_for_id;
  TileSet rel_tiles, extra_rel_tiles;
  std::unordered_map<osmium::object_id_type, std::unordered_set<osmium::object_id_type> > rel_members;

  iterate<osmium::Relation>(it, end, [&node_tiles, &way_tiles, &extra_node_tiles, &rel_tiles, &rel_members] (const osmium::Relation &rel) {
      if (rel.visible()) {
        const auto rel_id = rel.id();

        for (const auto &member : rel.members()) {
          const auto member_ref = member.ref();

          if (member.type() == osmium::item_type::node) {
            add_tiles_for_id(node_tiles, member_ref, rel_tiles, rel_id);
            add_tiles_for_id(extra_node_tiles, member_ref, rel_tiles, rel_id);

          } else if (member.type() == osmium::item_type::way) {
            add_tiles_for_id(way_tiles, member_ref, rel_tiles, rel_id);

          } else {
            rel_members[rel_id].insert(member_ref);
          }
        }
      }
    });

  for (const auto &rel_member : rel_members) {
    for (auto member_id : rel_member.second) {
      add_tiles_for_id(rel_tiles, member_id, extra_rel_tiles, rel_member.first);
    }
  }

  return std::move(std::make_pair(std::move(rel_tiles), std::move(extra_rel_tiles)));
}

} // namespace hsplitter

#endif /* OSMIUM_HISTORY_SPLITTER_SPLITTER_HPP */
