#ifndef OSMIUM_HISTORY_SPLITTER_TILE_MAP_ARRAY_HPP
#define OSMIUM_HISTORY_SPLITTER_TILE_MAP_ARRAY_HPP

/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <vector>
#include <memory>
#include <algorithm>
#include <iterator>

#include "chunked_array.hpp"

namespace hsplitter {

struct pair_snd_iterator {
  typedef container::chunked_array<std::pair<uint32_t, uint32_t> >::const_iterator const_iterator;
  explicit pair_snd_iterator(const_iterator i) : m_itr(i) {}
  pair_snd_iterator(const pair_snd_iterator &other) : m_itr(other.m_itr) {}

  typedef const uint32_t &reference;

  inline reference operator*() { return m_itr->second; }
  inline pair_snd_iterator &operator++() { ++m_itr; return *this; }
  inline pair_snd_iterator operator++(int) { pair_snd_iterator rv = *this; ++(*this); return rv; }

  inline bool operator==(const pair_snd_iterator &other) const { return m_itr == other.m_itr; }
  inline bool operator!=(const pair_snd_iterator &other) const { return m_itr != other.m_itr; }

private:
  const_iterator m_itr;
};

template <typename Iterator>
struct iter_pair_range {
  typedef std::pair<Iterator, Iterator> value_type;
  value_type m_pair;

  explicit iter_pair_range(value_type v) : m_pair(v) {}

  Iterator begin() const { return m_pair.first; }
  Iterator end()   const { return m_pair.second; }
};

struct tile_map_subarray {
  typedef uint32_t key_type;
  typedef uint32_t mapped_type;
  typedef pair_snd_iterator const_iterator;
  typedef container::chunked_array<std::pair<uint32_t, uint32_t> > cont_t;

  tile_map_subarray()
    : m_unsorted_count(0), m_array() {}
  tile_map_subarray(tile_map_subarray &&t)
    : m_unsorted_count(t.m_unsorted_count),
      m_array(std::move(t.m_array)) {
  }
  tile_map_subarray(const tile_map_subarray &) = delete;

  tile_map_subarray &operator=(tile_map_subarray &&t) {
    m_unsorted_count = t.m_unsorted_count;
    m_array = std::move(t.m_array);
    return *this;
  }
  tile_map_subarray &operator=(const tile_map_subarray &) = delete;

  void insert(key_type k, mapped_type v) {
    auto p = std::make_pair(k, v);
    if (m_array.empty() || p != m_array.back()) {
      if ((m_unsorted_count > 0) ||
          (!m_array.empty() && (m_array.back() > p))) {
        ++m_unsorted_count;
      }
      m_array.push_back(p);

      if (m_unsorted_count > 16777216) {
        size_t before = m_array.size();
        sort_array();
        size_t after = m_array.size();
        std::cerr << "too many unsorted, sorting! " << before << " -> " << after << std::endl;
      }
    }
  }

  void sort_array() const {
    //std::cerr << "sorting!" << std::endl;
    std::sort(m_array.begin(), m_array.end());
    auto itr = std::unique(m_array.begin(), m_array.end());
    //m_array.erase(itr, m_array.end());
    //m_array.shrink_to_fit();
    assert(itr == m_array.end()); // there were no duplicates
    m_unsorted_count = 0;
  }

  iter_pair_range<const_iterator> equal_range(key_type k) const {
    if (m_unsorted_count > 0) {
      sort_array();
    }
    const auto &lb = std::lower_bound(m_array.cbegin(), m_array.cend(), std::make_pair(k, mapped_type(0)));
    const auto &ub = std::upper_bound(lb, m_array.cend(), std::make_pair(k, std::numeric_limits<mapped_type>::max()));
    return iter_pair_range<const_iterator>(std::make_pair(const_iterator(lb), const_iterator(ub)));
  }

  mutable uint64_t m_unsorted_count;
  mutable cont_t m_array;
};

struct tile_map_array {
  typedef int64_t key_type;
  typedef uint32_t mapped_type;
  typedef pair_snd_iterator const_iterator;

  tile_map_array() {}
  tile_map_array(tile_map_array &&t) : m_array(std::move(t.m_array)) {}
  tile_map_array(const tile_map_array &) = delete;

  tile_map_array &operator=(tile_map_array &&t) { m_array = std::move(t.m_array); return *this; }
  tile_map_array &operator=(const tile_map_array &) = delete;

  void insert(key_type k, mapped_type v) {
    assert(k >= 0);
    uint64_t idx = k >> 24;
    uint32_t prt = k & ((uint64_t(1) << 24) - 1);
    //std::cerr << "insert(" << k << ", " << v << ") -> " << idx << ", " << prt << std::endl;
    if (idx >= m_array.size()) {
      m_array.resize(idx + 1);
    }
    tile_map_subarray &sub = m_array[idx];
    sub.insert(prt, v);
  }

  void freeze() {
    size_t size = 0, post_size = 0;
    for (tile_map_subarray &sub : m_array) {
      size += sub.m_array.capacity();
      sub.sort_array();
      post_size += sub.m_array.capacity();
    }
    size_t item_size = sizeof(tile_map_subarray::cont_t::value_type);
    std::cout << "pre-freeze size: " << (size * item_size) << std::endl;
    std::cout << "post-freeze size: " << (post_size * item_size) << std::endl;
    std::cout << "(freeze) item size: " << item_size << std::endl;
  }

  iter_pair_range<const_iterator> equal_range(key_type k) const {
    assert(k >= 0);
    uint32_t idx = k >> 24;
    uint32_t prt = k & ((uint64_t(1) << 24) - 1);
    if (idx >= m_array.size()) {
      return iter_pair_range<const_iterator>(std::make_pair(pair_snd_iterator(m_empty.end()), pair_snd_iterator(m_empty.end())));

    } else {
      const tile_map_subarray &sub = m_array[idx];
      return sub.equal_range(prt);
    }
  }

  std::vector<tile_map_subarray> m_array;
  static const tile_map_subarray::cont_t m_empty;
};

} // namespace hsplitter

#endif /* OSMIUM_HISTORY_SPLITTER_TILE_MAP_ARRAY_HPP */
