/*

This file is part of the Osmium History Splitter

Copyright 2015 Matt Amos <zerebubuth@gmail.com>.

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <string>
#include <cstdlib>
#include <set>
#include <osmium/osm/types.hpp>

inline std::string test_data_file(const std::string &path) {
  const char *dir = std::getenv("OSMIUM_HISTORY_SPLITTER_TEST_DATA_DIR");

  std::string file;
  if (dir != nullptr) {
    file.append(dir);
    file.append("/");
  }
  file.append(path);

  return file;
}

struct std_id_set {
  typedef osmium::object_id_type value_type;

  std::set<value_type> m_set;

  inline bool has(value_type x) const {
    return m_set.count(x) > 0;
  }

  inline void add(value_type x) {
    m_set.insert(x);
  }

  inline void add_all(const std_id_set &other) {
    for (value_type x : other.m_set) {
      add(x);
    }
  }
};
